services:
  andrey_db:
    image: postgres:latest
    restart: always
    container_name: andrey_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGPORT: 5545
    ports:
      - "5645:5545"
    volumes:
      - "andrey_volume:/var/lib/postgresql"

volumes:
  andrey_volume:
